import argparse
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset',default='movielens')
    parser.add_argument('--train_epoch',type=int,default=30)
    parser.add_argument('--batch_size',type=int,default=512)
    parser.add_argument('--regs',type=float,default=0.001)
    parser.add_argument('--model',default='model1')
    parser.add_argument('--local_lr',type=float,default=0.01)
    parser.add_argument('--global_lr',type=float,default=0.000001)
    parser.add_argument('--gpu_id',default=0)
    parser.add_argument('--number',default=0)
    parser.add_argument('--weight_init_std',type=float,default=0.01)
    parser.add_argument('--mod',default='train')
    parser.add_argument('--test_epoch',type=int,default=10)
    parser.add_argument('--topK',type=int,default=50)
    parser.add_argument('--num_negative_support',type=int,default=3)
    parser.add_argument('--num_negative_evaluation',type=int,default=200)
    parser.add_argument('--exp',default=False)
    parser.add_argument('--local_epoch',type=int,default=5)
    parser.add_argument('--global_lr_share',type=float,default=0.00001)
    return parser.parse_args()
